
# Generated by Django 5.1.3 on 2024-11-16 21:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('auth', '0012_alter_user_first_name_max_length'),

    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.TextField()),


                ('link', models.CharField(max_length=200)),

                ('publication_date', models.DateField(auto_now_add=True)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(

            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scientist', 'Scientist'), ('businessman', 'Businessman'), ('investor', 'Investor')], max_length=100)),
                ('open_for_contact', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('required_money', models.FloatField()),
                ('type', models.CharField(choices=[('startup', 'Startup'), ('working business', 'Working Business'), ('research', 'Research')], max_length=20)),
                ('brief', models.TextField()),
                ('project_scope', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profile')),
                ('profiles', models.ManyToManyField(related_name='projects', to='common.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=100)),
                ('message', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='common.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='common.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project')),
            ],
        ),
    ]
