# Generated by Django 5.1.3 on 2024-11-16 20:49

from django.db import migrations


def add_example_users(apps, schema_editor):
    CustomUser = apps.get_model('common', 'CustomUser')
    CustomUser.objects.create_superuser(
        username='biznes_user',
        email='biznes@example.com',
        password='biznes_user'
    )
    CustomUser.objects.create_superuser(
        username='nauka_user',
        email='nauka@example.com',
        password='nauka_user'
    )
    CustomUser.objects.create_superuser(
        username='invest_user',
        email='invest@example.com',
        password='invest_user'
    )

def remove_example_users(apps, schema_editor):
    CustomUser = apps.get_model('common', 'CustomUser')
    CustomUser.objects.filter(username='biznes_user').delete()
    CustomUser.objects.filter(username='nauka_user').delete()
    CustomUser.objects.filter(username='invest_user').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_example_users, remove_example_users),
    ]