# Generated by Django 5.1.2 on 2024-11-16 21:28

from django.db import migrations

def add_example_users(apps, schema_editor):
    # Get the CustomUser and Profile models
    CustomUser = apps.get_model('common', 'CustomUser')
    Profile = apps.get_model('common', 'Profile')

    # Create and associate profiles with existing users
    # Here we can create profiles for existing users and assign them different types

    user_1 = CustomUser.objects.get(username='biznes_user')
    Profile.objects.create(user=user_1, type='businessman', open_for_contact=True)

    user_2 = CustomUser.objects.get(username='nauka_user')
    Profile.objects.create(user=user_2, type='scientist', open_for_contact=True)

    user_3 = CustomUser.objects.get(username='invest_user')
    Profile.objects.create(user=user_3, type='investor', open_for_contact=True)

def remove_example_users(apps, schema_editor):
    # You can create a reverse function to delete the profiles if needed
    CustomUser = apps.get_model('common', 'CustomUser')
    Profile = apps.get_model('common', 'Profile')

    # Remove the profiles created in add_example_users
    Profile.objects.filter(user__username__in=['biznes_user', 'nauka_user', 'invest_user']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_BYHAND_create_custom_users'),
    ]

    operations = [
        migrations.RunPython(add_example_users, remove_example_users),
    ]
