# Generated by Django 5.1.3 on 2024-11-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('scientist', 'Scientist'), ('businessman', 'Businessman'), ('investor', 'Investor')], max_length=100),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('required_money', models.FloatField()),
                ('type', models.CharField(choices=[('startup', 'Startup'), ('working business', 'Working Business'), ('research', 'Research')], max_length=20)),
                ('brief', models.TextField()),
                ('project_scope', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.profile')),
                ('profiles', models.ManyToManyField(related_name='projects', to='common.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=100)),
                ('message', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='common.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='common.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project')),
            ],
        ),
    ]
