# Generated by Django 5.1.2 on 2024-11-16 23:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_BYHAND_create_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
    ]
