# Generated by Django 5.1.3 on 2024-11-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_paper_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='author',
        ),
    ]
