# Generated by Django 5.1.3 on 2024-11-16 23:48

from django.db import migrations

def add_random_names(apps, schema_editor):
    CustomUser = apps.get_model('common', 'CustomUser')

    # Update the users created in the 0003 migration
    user_1 = CustomUser.objects.get(username='biznes_user')
    user_1.first_name = 'John'
    user_1.last_name = 'Doe'
    user_1.save()

    user_2 = CustomUser.objects.get(username='nauka_user')
    user_2.first_name = 'Jane'
    user_2.last_name = 'Smith'
    user_2.save()

    user_3 = CustomUser.objects.get(username='invest_user')
    user_3.first_name = 'Alice'
    user_3.last_name = 'Johnson'
    user_3.save()

def remove_random_names(apps, schema_editor):
    CustomUser = apps.get_model('common', 'CustomUser')

    # Reset the names of the users created in the 0003 migration
    user_1 = CustomUser.objects.get(username='biznes_user')
    user_1.first_name = ''
    user_1.last_name = ''
    user_1.save()

    user_2 = CustomUser.objects.get(username='nauka_user')
    user_2.first_name = ''
    user_2.last_name = ''
    user_2.save()

    user_3 = CustomUser.objects.get(username='invest_user')
    user_3.first_name = ''
    user_3.last_name = ''
    user_3.save()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_paper_author'),
    ]

    operations = [
        migrations.RunPython(add_random_names, remove_random_names),
    ]
