# Generated by Django 5.1.3 on 2024-11-17 00:34

from django.db import migrations

def add_example_projects(apps, schema_editor):
    Project = apps.get_model('common', 'Project')
    Profile = apps.get_model('common', 'Profile')

    author = Profile.objects.get(user__username='biznes_user')

    projects = [
        {
            "title": "AI Startup",
            "content": "A startup focused on developing cutting-edge AI technologies.",
            "required_money": 500000.00,
            "type": "startup",
            "brief": "Innovative AI solutions for various industries.",
            "project_scope": "Develop AI models, deploy solutions, and scale the business.",
        },
        {
            "title": "Green Energy Initiative",
            "content": "A project aimed at promoting renewable energy sources.",
            "required_money": 750000.00,
            "type": "working business",
            "brief": "Sustainable energy solutions for a greener future.",
            "project_scope": "Install solar panels, wind turbines, and educate the public.",
        },
        {
            "title": "Quantum Computing Research",
            "content": "Research project focused on advancing quantum computing.",
            "required_money": 1000000.00,
            "type": "research",
            "brief": "Exploring the potential of quantum computing.",
            "project_scope": "Conduct experiments, publish findings, and collaborate with universities.",
        },
        {
            "title": "Blockchain for Healthcare",
            "content": "Implementing blockchain technology in healthcare.",
            "required_money": 600000.00,
            "type": "working business",
            "brief": "Secure and efficient healthcare data management.",
            "project_scope": "Develop blockchain solutions, integrate with existing systems, and ensure compliance.",
        },
        {
            "title": "Biotech Innovations",
            "content": "A project to develop new biotechnological solutions.",
            "required_money": 850000.00,
            "type": "research",
            "brief": "Innovative biotech solutions for healthcare and agriculture.",
            "project_scope": "Research and develop new biotech products, conduct trials, and bring products to market.",
        },
    ]

    for project_data in projects:
        Project.objects.create(
            author=author,
            title=project_data["title"],
            content=project_data["content"],
            required_money=project_data["required_money"],
            type=project_data["type"],
            brief=project_data["brief"],
            project_scope=project_data["project_scope"],
        )

def remove_example_projects(apps, schema_editor):
    Project = apps.get_model('common', 'Project')
    Project.objects.filter(
        title__in=[
            "AI Startup",
            "Green Energy Initiative",
            "Quantum Computing Research",
            "Blockchain for Healthcare",
            "Biotech Innovations",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_BYHAND_add_example_papers'),
    ]

    operations = [
        migrations.RunPython(add_example_projects, remove_example_projects),
    ]
