# Generated by Django 5.1.2 on 2024-11-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_BYHAND_add_example_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='projects', to='common.profile'),
        ),
    ]
