# Generated by Django 5.1.2 on 2024-11-17 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_BYHAND_add_example_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('fundings_gathered', models.FloatField()),
                ('end_date', models.DateField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project')),
            ],
        ),
    ]
