# Generated by Django 5.1.2 on 2024-11-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_BYHAND_add_example_papers_with_links'),
        ('common', '0009_BYHAND_add_example_projects'),
    ]

    operations = [
    ]
