# Generated by Django 5.1.3 on 2024-11-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brief', models.TextField()),
                ('link', models.URLField(default='https://arxiv.org/abs/1706.03762')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(default=dict)),
            ],
        ),
    ]
