# Generated by Django 5.1.3 on 2024-11-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbNaukowcy', '0002_rename_post_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='embedding',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(default='https://arxiv.org/abs/1706.03762'),
        ),
    ]
