# Generated by Django 5.1.3 on 2024-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbNaukowcy', '0003_publication_embedding_publication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='embedding',
            field=models.JSONField(default=dict),
        ),
    ]
