# Generated by Django 5.1.3 on 2024-11-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FbNaukowcy', '0004_alter_publication_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
